FROM mcr.microsoft.com/dotnet/sdk:8.0 as builder

WORKDIR /app

COPY . .

RUN dotnet restore

RUN dotnet build --no-restore -c Release -o /app/build

RUN dotnet publish --no-restore -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runner

WORKDIR /app

COPY --from=builder /app/publish .

EXPOSE 5000


CMD ["dotnet", "TWJbos.dll", "--urls", "http://0.0.0.0:5000"]